//! Drag input events.
//!
//! This module defines the input events for drag operations.
//! These are system-generated events that occur during a drag-and-drop
//! operation - distinct from mouse events because:
//!
//! 1. Drag has a payload (data being dragged)
//! 2. Normal hover/click behavior should be suppressed during drag
//! 3. Keyboard modifiers affect the drag action (Copy/Move/Link)
//!
//! Note: `DragStart` is NOT initiated by external input - it's triggered
//! by the application when it detects a drag gesture (mouse down + move
//! past threshold). These events track the drag *after* it has started.

use crate::keyboard::Modifiers;
use crate::Point;

use std::borrow::Cow;

/// A unique identifier for a drag operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct DragId(pub u64);

/// Information about the data being dragged.
///
/// This is a lightweight handle - the actual data is stored elsewhere
/// and can be requested via the runtime.
#[derive(Debug, Clone, PartialEq)]
pub struct DragOffer {
    /// Unique identifier for this drag operation.
    pub id: DragId,
    /// MIME types the dragged data is available in.
    pub mime_types: Vec<Cow<'static, str>>,
    /// Actions supported by the drag source.
    pub source_actions: Actions,
    /// Whether this is an internal (same-app) or external drag.
    pub internal: bool,
}

impl DragOffer {
    /// Check if the offer provides a specific MIME type.
    pub fn has_mime_type(&self, mime: &str) -> bool {
        self.mime_types.iter().any(|m| m.as_ref() == mime)
    }

    /// Check if text data is available.
    pub fn has_text(&self) -> bool {
        self.has_mime_type("text/plain")
            || self.has_mime_type("text/plain;charset=utf-8")
            || self.has_mime_type("UTF8_STRING")
    }

    /// Check if URI/file data is available.
    pub fn has_uris(&self) -> bool {
        self.has_mime_type("text/uri-list")
    }
}

bitflags::bitflags! {
    /// Actions that can be performed during a drag-and-drop operation.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
    pub struct Actions: u8 {
        /// No action.
        const NONE = 0;
        /// Copy the data.
        const COPY = 1 << 0;
        /// Move the data.
        const MOVE = 1 << 1;
        /// Create a link to the data.
        const LINK = 1 << 2;
        /// Ask the user what to do.
        const ASK = 1 << 3;
    }
}

impl Actions {
    /// Returns the preferred action based on keyboard modifiers.
    ///
    /// Common conventions:
    /// - Ctrl: Copy
    /// - Shift: Move
    /// - Ctrl+Shift or Alt: Link
    pub fn from_modifiers(modifiers: Modifiers) -> Self {
        if modifiers.control() && modifiers.shift() {
            Actions::LINK
        } else if modifiers.alt() {
            Actions::LINK
        } else if modifiers.control() {
            Actions::COPY
        } else if modifiers.shift() {
            Actions::MOVE
        } else {
            Actions::NONE // Use source default
        }
    }
}

/// The outcome of a drag operation.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Outcome {
    /// The drag was dropped and accepted with the given action.
    Accepted(Actions),
    /// The drag was cancelled or rejected.
    Cancelled,
}

/// A drag input event.
///
/// These events are generated by the system during a drag operation.
/// They provide position, keyboard modifiers, and access to the drag payload.
#[derive(Debug, Clone, PartialEq)]
pub enum Event {
    /// A drag operation has begun over this widget/window.
    ///
    /// This is sent when:
    /// - Internal: The mouse moved past the drag threshold while pressed
    /// - External: A drag from another app entered this window
    ///
    /// The `offer` contains information about the available data and actions.
    Begin {
        /// Current position of the drag cursor.
        position: Point,
        /// Keyboard modifiers currently held.
        modifiers: Modifiers,
        /// Information about the dragged data.
        offer: DragOffer,
    },

    /// The drag cursor moved.
    ///
    /// Sent repeatedly as the user moves the drag cursor.
    /// Use `modifiers` to determine the current action (Copy/Move/Link).
    Update {
        /// Current position of the drag cursor.
        position: Point,
        /// Keyboard modifiers currently held.
        modifiers: Modifiers,
    },

    /// The drag operation ended.
    ///
    /// This is sent when:
    /// - The user released the mouse button (drop attempted)
    /// - The drag was cancelled (Escape, focus lost, etc.)
    /// - The drag left the window (external only)
    ///
    /// If `outcome` is `Accepted`, the drop was successful and
    /// you should request the data via the runtime.
    /// If `outcome` is `Cancelled`, clean up any visual feedback.
    End {
        /// Final position of the drag cursor (if dropped).
        position: Option<Point>,
        /// Keyboard modifiers at the time of drop/cancel.
        modifiers: Modifiers,
        /// The outcome of the drag operation.
        outcome: Outcome,
    },
}

impl Event {
    /// Returns the position of this event, if available.
    pub fn position(&self) -> Option<Point> {
        match self {
            Event::Begin { position, .. } => Some(*position),
            Event::Update { position, .. } => Some(*position),
            Event::End { position, .. } => *position,
        }
    }

    /// Returns the keyboard modifiers for this event.
    pub fn modifiers(&self) -> Modifiers {
        match self {
            Event::Begin { modifiers, .. } => *modifiers,
            Event::Update { modifiers, .. } => *modifiers,
            Event::End { modifiers, .. } => *modifiers,
        }
    }
}
